-- Keybinds.dhall
-- All keybind definitions with defaults (70+ keybinds)
let Keybinds =
      { Type =
          { leader : Optional Text
          , app_exit : Optional Text
          , editor_open : Optional Text
          , theme_list : Optional Text
          , sidebar_toggle : Optional Text
          , scrollbar_toggle : Optional Text
          , username_toggle : Optional Text
          , status_view : Optional Text
          , session_export : Optional Text
          , session_new : Optional Text
          , session_list : Optional Text
          , session_timeline : Optional Text
          , session_fork : Optional Text
          , session_rename : Optional Text
          , session_delete : Optional Text
          , stash_delete : Optional Text
          , model_provider_list : Optional Text
          , model_favorite_toggle : Optional Text
          , session_share : Optional Text
          , session_unshare : Optional Text
          , session_interrupt : Optional Text
          , session_compact : Optional Text
          , messages_page_up : Optional Text
          , messages_page_down : Optional Text
          , messages_line_up : Optional Text
          , messages_line_down : Optional Text
          , messages_half_page_up : Optional Text
          , messages_half_page_down : Optional Text
          , messages_first : Optional Text
          , messages_last : Optional Text
          , messages_next : Optional Text
          , messages_previous : Optional Text
          , messages_last_user : Optional Text
          , messages_copy : Optional Text
          , messages_undo : Optional Text
          , messages_redo : Optional Text
          , messages_toggle_conceal : Optional Text
          , tool_details : Optional Text
          , model_list : Optional Text
          , model_cycle_recent : Optional Text
          , model_cycle_recent_reverse : Optional Text
          , model_cycle_favorite : Optional Text
          , model_cycle_favorite_reverse : Optional Text
          , command_list : Optional Text
          , agent_list : Optional Text
          , agent_cycle : Optional Text
          , agent_cycle_reverse : Optional Text
          , variant_cycle : Optional Text
          , input_clear : Optional Text
          , input_paste : Optional Text
          , input_submit : Optional Text
          , input_newline : Optional Text
          , input_move_left : Optional Text
          , input_move_right : Optional Text
          , input_move_up : Optional Text
          , input_move_down : Optional Text
          , input_select_left : Optional Text
          , input_select_right : Optional Text
          , input_select_up : Optional Text
          , input_select_down : Optional Text
          , input_line_home : Optional Text
          , input_line_end : Optional Text
          , input_select_line_home : Optional Text
          , input_select_line_end : Optional Text
          , input_visual_line_home : Optional Text
          , input_visual_line_end : Optional Text
          , input_select_visual_line_home : Optional Text
          , input_select_visual_line_end : Optional Text
          , input_buffer_home : Optional Text
          , input_buffer_end : Optional Text
          , input_select_buffer_home : Optional Text
          , input_select_buffer_end : Optional Text
          , input_delete_line : Optional Text
          , input_delete_to_line_end : Optional Text
          , input_delete_to_line_start : Optional Text
          , input_backspace : Optional Text
          , input_delete : Optional Text
          , input_undo : Optional Text
          , input_redo : Optional Text
          , input_word_forward : Optional Text
          , input_word_backward : Optional Text
          , input_select_word_forward : Optional Text
          , input_select_word_backward : Optional Text
          , input_delete_word_forward : Optional Text
          , input_delete_word_backward : Optional Text
          , history_previous : Optional Text
          , history_next : Optional Text
          , session_child_cycle : Optional Text
          , session_child_cycle_reverse : Optional Text
          , session_parent : Optional Text
          , terminal_suspend : Optional Text
          , terminal_title_toggle : Optional Text
          , tips_toggle : Optional Text
          , display_thinking : Optional Text
          }
      , default =
        { leader = Some "ctrl+x"
        , app_exit = Some "ctrl+c,ctrl+d,<leader>q"
        , editor_open = Some "<leader>e"
        , theme_list = Some "<leader>t"
        , sidebar_toggle = Some "<leader>b"
        , scrollbar_toggle = Some "none"
        , username_toggle = Some "none"
        , status_view = Some "<leader>s"
        , session_export = Some "<leader>x"
        , session_new = Some "<leader>n"
        , session_list = Some "<leader>l"
        , session_timeline = Some "<leader>g"
        , session_fork = Some "none"
        , session_rename = Some "ctrl+r"
        , session_delete = Some "ctrl+d"
        , stash_delete = Some "ctrl+d"
        , model_provider_list = Some "ctrl+a"
        , model_favorite_toggle = Some "ctrl+f"
        , session_share = Some "none"
        , session_unshare = Some "none"
        , session_interrupt = Some "escape"
        , session_compact = Some "<leader>c"
        , messages_page_up = Some "pageup,ctrl+alt+b"
        , messages_page_down = Some "pagedown,ctrl+alt+f"
        , messages_line_up = Some "ctrl+alt+y"
        , messages_line_down = Some "ctrl+alt+e"
        , messages_half_page_up = Some "ctrl+alt+u"
        , messages_half_page_down = Some "ctrl+alt+d"
        , messages_first = Some "ctrl+g,home"
        , messages_last = Some "ctrl+alt+g,end"
        , messages_next = Some "none"
        , messages_previous = Some "none"
        , messages_last_user = Some "none"
        , messages_copy = Some "<leader>y"
        , messages_undo = Some "<leader>u"
        , messages_redo = Some "<leader>r"
        , messages_toggle_conceal = Some "<leader>h"
        , tool_details = Some "none"
        , model_list = Some "<leader>m"
        , model_cycle_recent = Some "f2"
        , model_cycle_recent_reverse = Some "shift+f2"
        , model_cycle_favorite = Some "none"
        , model_cycle_favorite_reverse = Some "none"
        , command_list = Some "ctrl+p"
        , agent_list = Some "<leader>a"
        , agent_cycle = Some "tab"
        , agent_cycle_reverse = Some "shift+tab"
        , variant_cycle = Some "ctrl+t"
        , input_clear = Some "ctrl+c"
        , input_paste = Some "ctrl+v"
        , input_submit = Some "return"
        , input_newline = Some "shift+return,ctrl+return,alt+return,ctrl+j"
        , input_move_left = Some "left,ctrl+b"
        , input_move_right = Some "right,ctrl+f"
        , input_move_up = Some "up"
        , input_move_down = Some "down"
        , input_select_left = Some "shift+left"
        , input_select_right = Some "shift+right"
        , input_select_up = Some "shift+up"
        , input_select_down = Some "shift+down"
        , input_line_home = Some "ctrl+a"
        , input_line_end = Some "ctrl+e"
        , input_select_line_home = Some "ctrl+shift+a"
        , input_select_line_end = Some "ctrl+shift+e"
        , input_visual_line_home = Some "alt+a"
        , input_visual_line_end = Some "alt+e"
        , input_select_visual_line_home = Some "alt+shift+a"
        , input_select_visual_line_end = Some "alt+shift+e"
        , input_buffer_home = Some "home"
        , input_buffer_end = Some "end"
        , input_select_buffer_home = Some "shift+home"
        , input_select_buffer_end = Some "shift+end"
        , input_delete_line = Some "ctrl+shift+d"
        , input_delete_to_line_end = Some "ctrl+k"
        , input_delete_to_line_start = Some "ctrl+u"
        , input_backspace = Some "backspace,shift+backspace"
        , input_delete = Some "ctrl+d,delete,shift+delete"
        , input_undo = Some "ctrl+-,super+z"
        , input_redo = Some "ctrl+.,super+shift+z"
        , input_word_forward = Some "alt+f,alt+right,ctrl+right"
        , input_word_backward = Some "alt+b,alt+left,ctrl+left"
        , input_select_word_forward = Some "alt+shift+f,alt+shift+right"
        , input_select_word_backward = Some "alt+shift+b,alt+shift+left"
        , input_delete_word_forward = Some "alt+d,alt+delete,ctrl+delete"
        , input_delete_word_backward = Some
            "ctrl+w,ctrl+backspace,alt+backspace"
        , history_previous = Some "up"
        , history_next = Some "down"
        , session_child_cycle = Some "<leader>right"
        , session_child_cycle_reverse = Some "<leader>left"
        , session_parent = Some "<leader>up"
        , terminal_suspend = Some "ctrl+z"
        , terminal_title_toggle = Some "none"
        , tips_toggle = Some "<leader>h"
        , display_thinking = Some "none"
        }
      }

in  Keybinds
